In [2]:
import torch

print(torch.__version__)
print(torch.__file__)
print(torch.nn)

2.13.0+cpu
d:\AIML\projects\vibe-check-ai\.venv\Lib\site-packages\torch\__init__.py
<module 'torch.nn' from 'd:\\AIML\\projects\\vibe-check-ai\\.venv\\Lib\\site-packages\\torch\\nn\\__init__.py'>

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("data/raw/IMDB Dataset.csv")

In [5]:
df.shape

(50000, 2)

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(49582, 2)

## Preprocessing

### Converting To Lowercase

In [10]:
df["review"] = df["review"].str.lower()

### Removing The URLS

In [11]:
import re
sample_text = "abc is the word, abc" 
new_text = re.sub("abc", "xyz", sample_text)

In [12]:
new_text

'xyz is the word, xyz'

In [13]:
def remove_urls(text):
    re.sub(r"http\S+", "", text)
    return text

df["review"] = df["review"].apply(remove_urls)

### 3. Remove Punctuations

In [14]:
def remove_punctuation(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "", text)
    return text

df["review"] = df["review"].apply(remove_punctuation)

### 4. Remove HTML Tags

In [15]:
def remove_html(text):
    text = re.sub(r"<.*?>", "",text)
    return text

df["review"] = df["review"].apply(remove_html)

### 5. Removing The StopWords

In [16]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\athvi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\athvi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\athvi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [18]:
sample_text = "I like coding in Python. It is a great programming language."
tokens = word_tokenize(sample_text)
tokens

['I',
 'like',
 'coding',
 'in',
 'Python',
 '.',
 'It',
 'is',
 'a',
 'great',
 'programming',
 'language',
 '.']

In [19]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")
    return text

df["review"] = df["review"].apply(remove_stopwords)

In [20]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

### 6. Stemming

In [21]:
from nltk.stem import PorterStemmer

In [22]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

### 7. Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [24]:
y = df["sentiment"]

In [25]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8.Vectorization

In [26]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])

In [28]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057136 stored elements and shape (49582, 5000)>

In [29]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057136 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515484681268887
  (0, 2868)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3002)	0.47200539890110405
  (0, 1277)	0.1357698919196183
  (0, 2289)	0.049500237517476293
  (0, 1934)	0.0791260308382
  (0, 3550)	0.0963974330192639
  (0, 1363)	0.06162489377343992
  (0, 1963)	0.061560444992697486
  (0, 219)	0.08588920995304898
  (0, 1621)	0.0738170550485134
  (0, 4368)	0.041994187696759305
  (0, 4170)	0.17799685402440263
  (0, 3693)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3805)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1740)	0.037520883911174724
  (0, 4496)	0.07614066339174266
  (0, 3857)	0.17537900435282314
  (0, 1631)	0.06142445471882175
  (0, 1863)	0.07433134577032253
  (0, 3329)	0.06406818508428483
  (0, 3332)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1543)	0.17584072573791829
  (49581, 4493)	0.09410069396961679
  (49581, 435)	0.11251655954741112
  (49581, 4276)	0.10905956327445408
  (49581, 1958)	0.0999074542943991
  (49581, 556)	0.08424218838425554
  (49581, 2187)	0.14180348667063264
  (49581, 2217)	0.09535602544797335
  (49581, 4346)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3647)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1977)	0.1279546327938257
  (49581, 528)	0.1247934452922504
  (49581, 2621)	0.17341357547872566
  (49581, 4457)	0.16002233459530202
  (49581, 2174)	0.18983797727912208
  (49581, 4032)	0.20100044911463438
  (49581, 342)	0.14784964476913964
  (49581, 2695)	0.1740080872946952
  (49581, 440)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1765)	0.15815315432712562
  (49581, 3489)	0.1519741559925848

## Dataset And DataLoaders

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [31]:
X_train.shape

(39665, 5000)

In [32]:
X_test.shape

(9917, 5000)

In [33]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3248313 stored elements and shape (39665, 5000)>

In [34]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [35]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [37]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values.copy()).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values.copy()).float()
)

In [38]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=False, batch_size=64)

### Build Our RNN

In [41]:
import torch.nn as nn
import torch.optim as optim

In [42]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        #RNN Layer
        self.rnn = nn.RNN(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True
        )

        #Fully Connected Layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        #optional => shape (num_layers, batch_size, hidden_size)

        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0)
        # 1st value = hidden state of all the time steps => (batch, seq_len, hidden_size)
        # 2nd value = final hidden state of the last time step

        out = self.fc(out[:, -1, :])
        return out

In [43]:
input_size = X_train.shape[1]

model = RNN(input_size=input_size)

optimizer = optim.Adam(model.parameters())

## Training The RNN